#
# Module manifest for module 'VMware.VimAutomation.Custom'
#
# Generated by: David Cruz (davidcruz72@gmail.com)
#
# Generated on: 05.02.2018
#

@{

# Script module or binary module file associated with this manifest.
ModuleToProcess = 'VMware.VimAutomation.Custom.psm1'

# Version number of this module.
ModuleVersion = '1.2'

# Supported PSEditions
# CompatiblePSEditions = @()

# ID used to uniquely identify this module
GUID = '86c6095d-5954-4e26-956b-e6acdcb21eb9'

# Author of this module
Author = 'David Cruz (davidcruz72@gmail.com)'

# Company or vendor of this module
CompanyName = 'Community'

# Copyright statement for this module
Copyright = '(c) David Cruz (davidcruz72@gmail.com). All rights reserved.'

# Description of the functionality provided by this module
Description = 'This module extends the functionality of PowerCLI'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '5.0'

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# CLRVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
FormatsToProcess = 'format.ps1xml'

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = '*'

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = '*'

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = '*'

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        # Tags = @()

        ExternalModuleDependencies = @(@{ModuleName = 'VMware.PowerCLI'; ModuleVersion = '6.5.1'}, 'Posh-SSH')

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/Dapacruz/VMware.VimAutomation.Custom/blob/master/LICENSE'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/Dapacruz/VMware.VimAutomation.Custom'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        ReleaseNotes = '        
        Features:
        Get/Start/Stop ESXi host SSH service
        Get ESXi host uptime
        List ESXi host datastores
        Create a set of ESXi host networking CSV import templates
        Export ESXi host networking to CSV
        Import ESXi host networking from CSV
        Test ESXi host networking
        Calculate the virtual to physcial CPU ratio
        Display the CDP info for each vmnic
        Display the LLDP info for each vmnic
        Calculate virtual machine CPU ready percent average
        Enable and configure the software iSCSI adapter'

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}
